[project]
name = "portals"
version = "0.1.0"
description = ""
authors = [
    {name = "yel-gar"}
]
requires-python = ">=3.14,<4.0"
dependencies = [
    "fastapi (>=0.141.1,<0.142.0)",
    "sqlalchemy (>=2.0.54,<3.0.0)",
    "asyncpg (>=0.31.0,<0.32.0)",
    "uvicorn (>=0.53.0,<0.54.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[dependency-groups]
dev = [
    "black (>=26.5.1,<27.0.0)",
    "ruff (>=0.16.8,<0.17.0)",
    "pytest (>=9.1.1,<10.0.0)",
    "pre-commit (>=4.6.2,<5.0.0)",
    "coverage (>=7.16.1,<8.0.0)"
]

[tool.black]
line-length = 120
target-version = ["py314"]

[tool.ruff]
line-length = 120
target-version = "py314"

[tool.ruff.lint]
select = [
    "F",
    "E",
    "W",
    "I",
    "N",
    "UP",
    "B",
    "ASYNC",
    "C4",
    "PIE",
    "T20",
    "Q",
    "RET",
    "SIM",
    "ARG",
    "PTH",
    "RUF"
]
ignore = [
    "PIE796",
    "B028",
    "RUF018",
    "N818",
    "B905",
    "RUF012",
    "B008",
    "RUF001",
    "RUF200"
]

[tool.ruff.lint.per-file-ignores]
"tests/**/*.py" = ["ARG001"]

[tool.mypy]
python_version = "3.14"
strict = true
exclude = [
]
mypy_path = "app"

[[tool.mypy.overrides]]
module = ["tests.*"]
check_untyped_defs = true
disallow_untyped_defs = false

[tool.coverage.run]
source = ["app", "tests"]
branch = true

[tool.coverage.report]
show_missing = true
skip_covered = true
fail_under = 80

[tool.pytest.ini_options]
testpaths = ["tests"]
asyncio_mode = "auto"
asyncio_default_fixture_loop_scope = "session"
asyncio_default_test_loop_scope = "session"
