USERNAME_MIN_LENGTH = 4
USERNAME_MAX_LENGTH = 64

PASSWORD_MIN_LENGTH = 8
PASSWORD_MAX_LENGTH = 128
PASSWORD_HASH_MAX_LENGTH = 255

LOGIN_TOKEN_LENGTH = 64
SESSION_TTL_DAYS = 14

PORTAL_NAME_MAX_LENGTH = 128
DESTINATION_WORLD_MAX_LENGTH = 128

STABILITY_INCREASE_RAND_RANGE = (10, 30)
